import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";

const isProduction = process.argv[2] === 'production';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (name) => ({
	entryPoints: [`${name}.ts`],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: isProduction ? false : "inline",
	treeShaking: true,
	outfile: `${name}.js`,
	banner: {
		js: banner,
	},
});

const dev = (name) => ({
	...prod(name),
	sourcemap: "inline",
});

const build = isProduction ? prod : dev;

const builds = [
	build("main"),
];

const context = await esbuild.context({
	...builds[0],
	plugins: [{
		name: "watch",
		setup(build) {
			build.onEnd(() => {
				console.log(`Build finished at ${new Date(Date.now()).toLocaleTimeString()}`);
			});
		},
	}],
});

if (isProduction) {
	await Promise.all(builds.map(build => esbuild.build(build)));
} else {
	await context.watch();
	console.log("Watching for changes...");
}
